# GPU simulation of the Re = 100, 2D lid-driven cavity in the Rocky 2025 R1
# verification manual. Requires an NVIDIA GPU with CUDA.
#
# Generate the 1 cm input particles first (no GPU required), then run:
#     julia --project=gpu_version gpu_version/example/GenerateLidDrivenCavity2D.jl
#     julia --project=gpu_version gpu_version/example/LidDrivenCavity2d.jl
#
# The top wall has a prescribed horizontal velocity but does not translate out
# of the cavity (`MoveParticles = false`). The default duration is the 60 s
# specified by ANSYS. Optional arguments are [save_dir] [dx] [duration]
# [input_dir].
using SPHExampleGPU
using StaticArrays: SVector

include(joinpath(@__DIR__, "GenerateLidDrivenCavity2D.jl"))

"""
    run_lid_driven_cavity_2d(; FloatType = Float32, dx = 0.01,
        simulation_time = 60.0, output_interval = 0.5, visualize = true,
        open_log_file = true, input_dir, save_location)

Run the Re = 100 cavity using the particle CSVs generated by
`GenerateLidDrivenCavity2D.jl`. Returns the final `particles` and `meta`.
"""
function run_lid_driven_cavity_2d(; FloatType = Float32, dx = 0.01,
                                  simulation_time = 60.0, output_interval = 0.5,
                                  visualize::Bool = true, open_log_file::Bool = true,
                                  input_dir = normpath(joinpath(
                                      @__DIR__, "..", "input", "lid_driven_cavity_2d_generated")),
                                  save_location = raw"C:\TestSimulations\LidDrivenCavity2D_GPU")
    (isfinite(simulation_time) && simulation_time > 0) ||
        throw(ArgumentError("simulation_time must be finite and positive"))
    (isfinite(output_interval) && output_interval > 0) ||
        throw(ArgumentError("output_interval must be finite and positive"))

    prefix = joinpath(input_dir, "LidDrivenCavity2D_Dp$(dx)")
    input_files = ["$(prefix)_Fixed.csv", "$(prefix)_Lid.csv", "$(prefix)_Fluid.csv"]
    all(isfile, input_files) ||
        throw(ArgumentError("cavity particles are missing; generate them with " *
                            "`example/GenerateLidDrivenCavity2D.jl` at dx = $dx"))

    T = FloatType
    SimConstants = lid_driven_cavity_2d_constants(T; dx)
    simulation_geometry = [
        SPHGeometry{2, T}(CSVFile = input_files[1], GroupMarker = 1, Type = Fixed),
        SPHGeometry{2, T}(CSVFile = input_files[2], GroupMarker = 2, Type = Moving,
            Motion = MotionDetails{2, T}(
                Velocity = T(LID_CAVITY_LID_SPEED),
                StartTime = zero(T),
                Duration = T(simulation_time),
                Direction = SVector{2, T}(one(T), zero(T)),
                MoveParticles = false,
            )),
        SPHGeometry{2, T}(CSVFile = input_files[3], GroupMarker = 3, Type = Fluid),
    ]

    mkpath(save_location)
    meta = SimulationMetaData{2, T, NoShifting, NoKernelOutput, NoMDBC, StoreLog}(
        SimulationName = "LidDrivenCavity2D",
        SaveLocation = save_location,
        SimulationTime = T(simulation_time),
        OutputTimes = T(output_interval),
        VisualizeInParaview = visualize,
        ExportSingleVTKHDF = true,
        OpenLogFile = open_log_file,
    )
    particles = AllocateDataStructures(simulation_geometry, meta)
    logger = SimulationLogger(save_location; to_console = true)
    kernel = SPHKernelInstance{2, T}(WendlandC2();
                                     h = T(1.2 * sqrt(2) * dx))

    RunSimulation(
        SimGeometry = simulation_geometry,
        SimMetaData = meta,
        SimConstants = SimConstants,
        SimKernel = kernel,
        SimLogger = logger,
        SimParticles = particles,
        SimViscosity = Laminar(),
        SimDensityDiffusion = ZeroDensityDiffusion(),
        SimTimeStepping = SymplecticTimeStepping(),
    )
    return (; particles, meta)
end

if abspath(PROGRAM_FILE) == abspath(@__FILE__)
    save_location = length(ARGS) >= 1 ? ARGS[1] :
                    raw"C:\TestSimulations\LidDrivenCavity2D_GPU"
    dx = length(ARGS) >= 2 ? parse(Float64, ARGS[2]) : 0.01
    simulation_time = length(ARGS) >= 3 ? parse(Float64, ARGS[3]) : 60.0
    input_dir = length(ARGS) >= 4 ? ARGS[4] :
                normpath(joinpath(@__DIR__, "..", "input", "lid_driven_cavity_2d_generated"))
    run_lid_driven_cavity_2d(; save_location, dx, simulation_time, input_dir)
end
